apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: v1
kind: Pod
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  serviceAccountName: httpbin
  containers:
  - image: docker.io/mirantistraining/httpbin:1.0
    imagePullPolicy: IfNotPresent
    name: httpbin
    ports:
    - containerPort: 80
